import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";

import FirstSection from "../sections/firstSection/FirstSection";
import { SecondSection } from "../sections/secondSection/SecondSection";
import { ThirdSection } from "../sections/thirdSection/ThirdSection";
import { FormSection } from "../sections/FormSection/FormSection";
import { TopArrow } from "../components/TopArrow";
import Menu from "../sections/menu/Menu";
import { Box, CircularProgress } from "@mui/material";
import { useRouter } from "next/router";
import { Button } from "@mui/material";

import { ru, en } from "../translations";

const siteTitle = "GreenGo";

export default function Home({ title = siteTitle }) {
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [loader, setLoader] = useState(true);

  const closeMenu = () => setMenuOpen(false);

  const openMenu = () => setMenuOpen(true);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoader(false);
    }
  }, []);
  const router = useRouter();
  const { locale } = router;

  const t = locale === "ru" ? "ru" : "en";

  const handelLanguageToggle = () => {
    console.log("handelLanguageToggle");
    switch (locale) {
      case "ru":
        router.push("/", "/", { locale: "en" });
        break;
      case "ru":
        router.push("/", "/", { locale: "ru" });
        break;
    }
  };

  return (
    <Box>
      {loader ? (
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100vh",
            flexDirection: "column",
          }}
        >
          <CircularProgress />
        </Box>
      ) : (
        <Box>
          <div className="o-scroll" id="js-scroll" data-scroll-container>
            <Head>
              <title>{title} | GreenGo </title>
              <meta name="description" content="Generated by create next app" />
              <meta
                name="viewport"
                content="width=device-width, initial-scale=1"
              />
              <link rel="icon" href="/favicon.ico" />
            </Head>

            <Navbar
              onMenuIconClick={openMenu}
              close={closeMenu}
              isOpen={isMenuOpen}
            />

            <FirstSection />

            <SecondSection />

            <ThirdSection />
            <section className={{ textAlign: "center" }} data-scroll-section>
              <h1>2222{t.welcome}222</h1>

              <Button
                className="test"
                onClick={() => console.log("handelLanguageToggle")}
                variant="outlined"
              >
                1111 {locale} 1111
              </Button>
            </section>

            <ThirdSection />

            <FormSection />

            <TopArrow />
          </div>
        </Box>
      )}
    </Box>
  );
}
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...await serverSideTranslations(locale, ['common']),
  },
})
