import React, { useEffect, useState } from "react";
import Head from "next/head";
import Navbar from "../components/Navbar";
import { Box, Button, Grid, Typography } from "@mui/material";

import ModalWindow from "../components/modalWindow/form";

import { TopArrow } from "../components/TopArrow";
import { Footer } from "../footer/Footer";

import { useRouter } from "next/router";

import { useTranslation, Trans } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { AccordionSection } from "../sections/accordionSection/AccordionSection";

const siteTitle = "questions";

export default function Questions({ title = siteTitle }) {
  const { t } = useTranslation("common");
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [loader, setLoader] = useState(true);

  const [open, setOpen] = useState(false);
  const handleClickOpen = () => {
    // console.log("handleClickOpen setOpen = ", open);
    setOpen(true);
  };
  const handleClose = () => {
    setOpen(false);
  };

  const closeMenu = () => setMenuOpen(false);
  const openMenu = () => setMenuOpen(true);

  useEffect(() => {
    if (typeof window !== "undefined") {
      setLoader(false);
    }
  }, []);
  const router = useRouter();
  const { locale } = router;

  const handelLanguageToggle = (newLocale) => {
    const { pathname, asPath, query } = router;
    router.push({ pathname, query }, asPath, { locale: newLocale });
  };

  const changeTo = router.locale === "ru" ? "en" : "ru";

  const [header, setHeader] = useState("headerColor");

  const listenScrollEvent = (event) => {
    const bgColorChanged = 373;

    if (window.scrollY < bgColorChanged) {
      return setHeader("headerColor");
    } else if (window.scrollY > bgColorChanged) {
      return setHeader("headerColor2");
    }
  };

  return (
    <Box>
      <Head>
        <title>{title} | GreenGo </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box className={header}>
        <Navbar
          onMenuIconClick={openMenu}
          close={closeMenu}
          isOpen={isMenuOpen}
          languageToggle={handelLanguageToggle}
          // sx={{ border: "1px solid red" }}
        />
      </Box>

      <Box sx={{ height: "calc(100vh - 64px)" }}>
        <div id="top-page" />
        <AccordionSection />

        <Box
          className="container-box"
          sx={{
            alignItems: "center",
            marginBottom: "30px !important",
            flexDirection: "column  !important",
          }}
        >
          <Typography variant="body" gutterBottom sx={{ color: "black" }}>
            {/* Если вы не нашли ответ на свой вопрос, мы будем рады ответить на
            него */}
            {t("not_find_answer")}
          </Typography>

          <Button
            className="btn-contacts"
            variant="contained"
            onClick={handleClickOpen}
          >
            {/* Связаться с нами */}
            {t("contact_us")}
          </Button>

          <ModalWindow open={open} handleClose={handleClose} />
        </Box>

        <Footer />
        <TopArrow />
      </Box>
    </Box>
  );
}
export const getStaticProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});
